### PR TITLE
Add Pipfile and Pipfile.lock for pipenv integration

### PR DESCRIPTION
**Pull request by rodxavier**
This PR adds `Pipfile` and `Pipfile.lock` for pipenv integration. I generated `requirements.txt` and `requirements-dev.txt` from the lock file. I locked `ecpy` to 0.8.2 as it's the last version that supports python 2.

Partially solves #81 
I updated travis to use pipenv
I didn't add linting via flake8 in the travis config since when I run it locally, there's a lot of errors.

### CODE REVIEW

**Comment by roks0n** [comment]
You can also run pep8 for the git diff alone, eg `git diff upstream/aip11 arky tests | flake8 ... --diff`. Should be the best approach, otherwise, it would take too much time to fix all linting errors. :)

We should also open a debate what things we want to ignore, eg. do we want to use tabs or spaces given the whole project has tabs etc.

**Comment by Moustikitos** [comment]
Okay, have a read on your work.

As far as i can see, the `responses` package is only used on the unittest suit. So i think it is better to put it under `[dev-packages]` tag since pipenv allows us to differenciate development dependencies.

**Comment by rodxavier** [comment]
Alright. I'll move it to the dev-packages.

**Comment by rodxavier** [comment]
@Moustikitos done moving responses to dev packages

**Comment by roks0n** [comment]
Given we're not locking packages to a specific version in `Pipfile`, can't this cause issues?

**Comment by Moustikitos** [comment]
@roks0n The distributed package will not include test suite so i think not.
nide update !

**Pull request merged**
