### PR TITLE
Refactor account link

### PR DESCRIPTION
**Pull request by dunnen**
I refactored the link() because flake8 was complaining about its complexity. I broke out some pieces into two helper functions. One is for linking from a \<secret\> and the other is for linking from a file.   I also flipped some if-statements around to minimize if-else nesting. 

Two commits were not related to refactoring the link function but didn't seem like enough to warrant their own PR. 
1. I fixed the encoding comment at the type of the python files. Emacs was complaining every time I opened a file. Note: setup.py had the right encoding keyword.
2. I added pytest_cache/ to .gitignore.

### CODE REVIEW

**Comment by Moustikitos** [comment]
okay, seems good to me.

have you tried linking account and escrowed account ?

**Comment by dunnen** [comment]
I did both accounts and a \<2ndSecret\>. I did have a question about the second parameter for lin. Why can't a \<2ndSecret\> be passed along with --escrow?

**Comment by Moustikitos** [comment]
because if an account is escrowed, it already have a second secret

**Comment by Moustikitos** [comment]
if you have an account with 2 secret, you can link it using --escrow option
the only command available with escrow is to validate (second sign) transaction found in a registry file

**Comment by dunnen** [comment]
Ok. Hold off on this PR and let me play around with 2ndSecret and escrow a little more.

**Comment by Moustikitos** [comment]
okay

**Pull request merged**
