### PR TITLE
Improve readability and refactor request to peer and seed

### PR DESCRIPTION
**Pull request by yograterol**
`requests` library has its own method to convert from JSON to `dict`

### CODE REVIEW

**Comment by Moustikitos** [comment]
Hi yograterol,

thanks for your updates. I do not write code according to PEP8 proposal.
i'm okay for PEP8 compliance but keep tab spaces for identing (it is okay with PEP8 :)

What does `pip insall -e .` ?

thanks

**Comment by yograterol** [comment]
@Moustikitos hi,

About tabs, yes you're right but the indentation would be 4 spaces not 8. https://www.python.org/dev/peps/pep-0008/#indentation.

`pip install -e .`, install al requirements for the project from setup.py without install the current project.

**Comment by Moustikitos** [comment]
Okay, the number of spaces is something you can tweak on your editor (i use 4 spaces options)
Don't know how to tweak it on github.

Redo a pull request keeping your refactor and using tabs.

**Comment by yograterol** [comment]
That's the problem with tab, it is relative to the editor :joy:

I will try it.

**Comment by Moustikitos** [comment]
thanks, will merge as soon as you put tabs ;)
 thanks

**Comment by yograterol** [comment]
@Moustikitos done

**Comment by Moustikitos** [comment]
thanks !
nice job

**Comment by boldninja** [comment]
@Moustikitos can you put +5 to accepted PRs as so I can track them better for end of the month?

**Comment by Moustikitos** [comment]
+5

**Pull request merged**
