### PR TITLE
Fix/osx compatibility issue

### PR DESCRIPTION
**Pull request by peterdouglas**
This PR includes the following;
- fix so that arky works on osx
  - confirmed to work with both python 2.7 and python 3
- update readme.

Thanks!

### CODE REVIEW

**Comment by Moustikitos** [comment]
hi,
please, do not change `setup.py` file
thanks

**Comment by peterdouglas** [comment]
Will make sure I don't do it in the future. All of the changes were undone before making the PR though.
Let me know if there is anything else. :)

**Comment by Moustikitos** [comment]
+5

**Comment by boldninja** [comment]
@peterdouglas Can you provide me with your permanent ARK address for GitHub bounty distribution?

**Pull request merged**
