### PR TITLE
Added slices, AttributeError, update unittest

### PR DESCRIPTION
**Pull request by Yoiro**
Hello,

Corrected some stuff that made the code harder to read (basically, replacing some list comprehension with slicing), added the raising of an Error for getArkFiatPrice and getArkPriceFromCryptoCompare. Also added those raisings in the util tests.

### CODE REVIEW

**Comment by Moustikitos** [comment]
+5

**Comment by boldninja** [comment]
@Yoiro can you provide me with your Ark address? Thank you!

**Comment by Yoiro** [comment]
@boldninja  sure, here it is: AbbJgzh58sAJMTpJvWQ1gJbecCaJjcA5rm
Much thanks :+1: !

**Comment by boldninja** [comment]
sent - keep up the good work.

**Pull request merged**
