### PR TITLE
Added missing line for sending transactions

### PR DESCRIPTION
**Pull request by slydamus**
It would be good to have function for sending transactions in
core functions of the arky.

### CODE REVIEW

**Comment by Moustikitos** [comment]
Hi slydamus,

I separated the core and the api for future improvements.
Thanks for the update.

**Comment by Moustikitos** [comment]
+5

**Comment by boldninja** [comment]
@slydamus can you provide me your ARK address?

**Comment by slydamus** [comment]
Sure,
AJbGf1K5YEPaUyXXfPPdvYUBxcCycgzpiW

Thank you and keep up with the good work :)

**Pull request merged**
