### PR TITLE
Address validity with exceptions

### PR DESCRIPTION
**Pull request by illogicalextend**

### CODE REVIEW

**Comment by illogicalextend** [comment]
FYI this is actually my first contribution to an open source project, so I'm still getting used to things. Although if there's still something not done in the best way, feel free to take over and I can read over your commits.

**Comment by Moustikitos** [comment]
hi, you will do it :)

```
tx_in = ...
if isinstance(tx_in, list) and len(tx_in):
    ...
else:
    raise Exception(tx_in.get("error", "API error")

tx_out = ...
if isinstance(tx_out, list) and len(tx_out):
    ...
else:
    raise Exception(tx_out.get("error", "API error")

tx_in += [t for t in tx_out if t not in tx_in]
if not len(tx_in):
    raise Exception("No transactions for address %s" % address)

...
```

**Comment by fix** [comment]
@arky this PR sounds good to me. Waiting for your OK before merging.

Also, giving you rights on this repo

**Comment by Moustikitos** [comment]
+5

**Pull request merged**
